#!/bin/bash

# Standard shell sanity...
alias ls='ls -Gh'
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# Git make-nicer
alias gts="git status -s -b --column"
alias gtc="git checkout"
alias gtl="git log --graph --decorate=full"
alias gtlt="git log --graph --full-history --all --color --pretty=format:"%x1b[31m%h%x09%x1b[32m%d%x1b[0m%x20%s""
alias gtb="git branch -vva"
alias man='man -P most'

# PROMPT
export PS1="\u \W # "
